version: '3.8'

services:
  orders-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: orders-service
    ports:
      - "8081:8081"
    environment:
      - JAVA_OPTS=-Xmx512m
      - SPRING_DATASOURCE_URL=jdbc:postgresql://orders-postgres:5432/orders
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    depends_on:
      - orders-postgres
    restart: unless-stopped
  orders-postgres:
    image: postgres:13
    container_name: orders-postgres
    restart: always
    environment:
      POSTGRES_DB: orders
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"

volumes:
  postgres_data:
    driver: local